<?php

namespace abs\fivepointsBundle\Repository;

/**
 * conversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class conversationRepository extends \Doctrine\ORM\EntityRepository
{
}
